# C'est un workflow de base pour vous aider à démarrer avec Actions

name: CI Building Dart

# Contrôle quand le workflow sera exécuté
on:
  # Déclenche le workflow sur les événements push ou pull request mais seulement pour la branche master
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Permet de lancer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:
    inputs:
      confirm_run:
        type: string
        description: 'Tapez "oui" pour exécuter le deuxième job.'
        required: true
        default: 'non'
      version:
        description: 'Entrer numéro de version'
        required: true
        default: 0.0.0


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        sdk: [3.3.1]
        include:
          - os: ubuntu-latest
            output-name: gba-wav-to-s3m-converter
            alias: linux
          - os: macOS-latest
            output-name: gba-wav-to-s3m-converter
            alias: macOS
          - os: windows-latest
            output-name: gba-wav-to-s3m-converter.exe
            alias: windows
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1.6.4
        with:
          sdk: ${{ matrix.sdk }}
      
      - name: Install dependencies
        run: dart pub get
        
      - name: Create versioned build directory
        run: mkdir -p build/${{ matrix.alias }}

      - name: Compile applications
        run: dart compile exe ./bin/core/main.dart -o ./build/${{ matrix.alias }}/${{ matrix.output-name }}

      - name: Copy LICENSE file
        run: cp LICENSE ./build/${{ matrix.alias }}/LICENSE.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: gba-wav-to-s3m-converter-${{ matrix.alias }}-${{ github.event.inputs.version }}          
          path: build/${{ matrix.alias }}
                
  release:
    if: ${{ github.event.inputs.confirm_run == 'oui' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   
      
      - uses: actions/download-artifact@v4.1.7
        with:
          path: build

      - name: List files in build directory
        run: ls -R build/

      - name: List files in release directories
        run: |
          ls -la build/gba-wav-to-s3m-converter-linux-${{ github.event.inputs.version }}
          ls -la build/gba-wav-to-s3m-converter-macOS-${{ github.event.inputs.version }}
          ls -la build/gba-wav-to-s3m-converter-windows-${{ github.event.inputs.version }}

      - name: Zip the executables for Linux
        run: zip -j ./build/gba-wav-to-s3m-converter-linux-${{ github.event.inputs.version }}.zip ./build/gba-wav-to-s3m-converter-linux-${{ github.event.inputs.version }}/*
        shell: bash

      - name: Zip the executables for macOS
        run: zip -j ./build/gba-wav-to-s3m-converter-macOS-${{ github.event.inputs.version }}.zip ./build/gba-wav-to-s3m-converter-macOS-${{ github.event.inputs.version }}/*
        shell: bash

      - name: Zip the executables for Windows
        run: zip -j ./build/gba-wav-to-s3m-converter-windows-${{ github.event.inputs.version }}.zip ./build/gba-wav-to-s3m-converter-windows-${{ github.event.inputs.version }}/*
        shell: bash


      - name: Create and upload release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: |
            ./build/gba-wav-to-s3m-converter-linux-${{ github.event.inputs.version }}.zip
            ./build/gba-wav-to-s3m-converter-macOS-${{ github.event.inputs.version }}.zip
            ./build/gba-wav-to-s3m-converter-windows-${{ github.event.inputs.version }}.zip
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: 'Release version ${{ github.event.inputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
   
