# This is a basic workflow to help you get started with Actions

name: CI Building Dart

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: gba-wav-to-s3m-converter-linux
          - os: macOS-latest
            output-name: gba-wav-to-s3m-converter-mac
          - os: windows-latest
            output-name: gba-wav-to-s3m-converter-windows.exe
    steps:
          - uses: actions/checkout@v4
          - uses: dart-lang/setup-dart@v1.3
          
          - name: Install dependencies
            run: dart pub get
            
          - name: Extract version
            run: echo "VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2)" >> $GITHUB_ENV
            
          - run: mkdir -p build

          - name: Compile applications
          - run: dart compile exe ./bin/core/main.dart -o ./build/${{ matrix.output-name }}
          
          - name: Configure git
            run: |
              git config user.name 'github-actions'
              git config user.email 'github-actions@github.com'

          - name: Commit and push build directory
            run: |
              git add build/
              git commit -m "Add compiled executables for release ${GITHUB_SHA}"
              git push
